#version 450
#extension GL_EXT_shader_explicit_arithmetic_types : require
#extension GL_EXT_integer_dot_product : require

#ifndef USE_SUBGROUP_ADD_NO_SHMEM
#define USE_SUBGROUP_ADD_NO_SHMEM 1
#endif
#define MMQ
#define B_TYPE block_q8_1_x4

#include "mul_mat_vec_base.glsl"
#include "mul_mmq_funcs.comp"

layout(local_size_x_id = 0, local_size_y = 1, local_size_z = 1) in;

FLOAT_TYPE temp[NUM_COLS][NUM_ROWS];

void compute_outputs(const uint32_t first_row, const uint32_t num_rows) {
    uint a_offset, b_offset, d_offset;
    get_offsets(a_offset, b_offset, d_offset);

    const uint num_blocks_per_row = p.ncols / QUANT_K;

    [[unroll]] for (uint j = 0; j < NUM_COLS; ++j) {
        [[unroll]] for (uint i = 0; i < NUM_ROWS; ++i) {
            temp[j][i] = FLOAT_TYPE(0);
        }
    }

    const uint tid     = gl_LocalInvocationID.x;
    const uint k       = (tid % 8) * 4;
    const uint vec_idx = k / 4;        
    const uint ib0_base = a_offset / QUANT_K + first_row * num_blocks_per_row;

    for (uint jcol = 0; jcol < NUM_COLS; jcol++) {
        const uint b_base = (jcol * p.batch_stride_b);

        for (uint i = tid/8; i < num_blocks_per_row; i += gl_WorkGroupSize.x/8) {
            [[unroll]] for (uint h = 0; h < 2; ++h) {
                const uint j = h * 32u;

                const uint b_first = b_offset + (b_base + i * QUANT_K + j * 4u) / QUANT_K_Q8_1;
                const uint b_outer = b_first / 4u;

                [[unroll]] for (uint qpair = 0; qpair < 2; ++qpair) {
                    const uint q0 = qpair * 2u;
                    const uint q1 = q0 + 1u;

                    const vec2 dsa = vec2(data_b[b_offset + b_outer].ds[q0]);
                    const vec2 dsb = vec2(data_b[b_offset + b_outer].ds[q1]);

                    const int32_t ba = data_b[b_offset + b_outer].qs[q0 * 8u + vec_idx];
                    const int32_t bb = data_b[b_offset + b_outer].qs[q1 * 8u + vec_idx];

                    [[unroll]] for (uint n = 0; n < NUM_ROWS; ++n) {
                        if (n >= num_rows) { continue; }

                            const uint  ib0    = ib0_base + n * num_blocks_per_row;
                            const float d      =  float(data_a[ib0 + i].d);
                            const float d_neg8 = -d * 0.125f;

                            const uint a_h_idx = (j + k) >> 1u;
                            const uint a_lo    = uint(data_a_packed16[ib0 + i].qs[a_h_idx    ]);
                            const uint a_hi    = uint(data_a_packed16[ib0 + i].qs[a_h_idx + 1]);
                            const uint v       = a_lo | (a_hi << 16);

                            const int32_t aa = int32_t((v >> (q0 * 2u)) & 0x03030303u);
                            const int32_t ab = int32_t((v >> (q1 * 2u)) & 0x03030303u);

                            FLOAT_TYPE acc = temp[jcol][n];
                            acc += ACC_TYPE(float(dotPacked4x8EXT(aa, ba)) * d * dsa.x + d_neg8 * dsa.y);
                            acc += ACC_TYPE(float(dotPacked4x8EXT(ab, bb)) * d * dsb.x + d_neg8 * dsb.y);
                            temp[jcol][n] = acc;
                        }
                }
            }
        }
    }

    reduce_result(temp, d_offset, first_row, num_rows, tid);
}

void main() {
    const uint first_row = NUM_ROWS * (gl_WorkGroupID.x + gl_NumWorkGroups.x * gl_WorkGroupID.z);

    if (first_row + NUM_ROWS <= p.stride_d) {
        compute_outputs(first_row, NUM_ROWS);
    } else {
        if (first_row >= p.stride_d) {
            return;
        }
        compute_outputs(first_row, p.stride_d - first_row);
    }
}
